# Using external libraries

As you've seen so far, writing code can be hard. It gets even harder when you're doing weird math things and you need it to be fast, easy to use, and error free. Fortunately we don't have to write everything from scratch ourselves: we can use libraries!

Libraries (or modules) are code that other people (or past you!) have written and packaged up in a neat and tidy way. This lets you call functions that they have written (remember yesterday?) to do things you want to do.

We will use the numpy module today to get used to the idea of using other people's code, and because it is super useful. Numpy stands for 'numerical python'. It is a super popular python library that does a lot of basic math things efficiently and accurately, allowing programmers to focus on more interesting problems.

**Lesson overview**

* What are modules?
* Lists vs Arrays
* Array operations (ex: sum, mean, sort)


### Lesson:

`numpy` is a python `library` or `module`, which is a fancy word for a set of code (developed by others) which you can use yourself. You already used a `numpy` function in Module 4, when you generated a random number for the guessing game!

**Modules are a collection of tools written in python** that is maintained and developed by the community. Often these modules come by default with any installation of python. However, if it exists on the internet, you can likely download it and use it.

Two common modules that are, by default, downloaded when you install python include `numpy` and `matplotlib`. We will focus on `numpy` here, but you will get an introduction to plotting with `matplotlib` in a later lesson.

### So `numpy` is a module, or a collection of code. How do we use it?

To use a module, you use the keyword `import`, which will load that module. Importing tells python to give you access to the code in that module. You can also import specific functions to save time if you don't need access to the entire module.

It is traditional when importing `numpy` to rename it to `np` using the `as` keyword. For example, the code would be
```python
import numpy as np
```
Notice the blue words are the python "keywords", basically saying that they have special meaning (and you can't use them as variable names).

Literally everyone renames `numpy` as `np`. This saves some typing and the meaning is clear. In fact, you can rename any module to anything you like using the `as` keyword, but it's useful to follow convention. If you do not use `as`, the module will be imported but not renamed.

*Let's try it out.*

Typically, people put all their imports in a cell at the top of their notebooks. So if you want to import any modules in the future, you'll want to put it here.

In [ ]:
import numpy as np

## Why do we care about `numpy`?

`numpy` can do a lot of cool things much, much, *much* faster than if you did them by hand in python. Mostly, it is fast because you can do things in one line that typically require loops. Most scientists use `numpy`.

Let's explore some of these benefits.

**Exercise:** Make a new list where every element is twice that of the original list. To do so, use a loop to iterate through every element in `mylist` and multiply that element by 2. Save that value to a new list and print it at the end.

In [ ]:
mylist = [1, 2, 3, 4, 5]
# double the above list element by element and print it here
for i in range(len(mylist)):
  mylist[i] = mylist[i] * 2
print(mylist)

[2, 4, 6, 8, 10]


In [ ]:
# workspace as necessary

[ 2  4  6  8 10]


To use `numpy` in your code, use `np` (you renamed it) and a period `.` afterward, which specifies you want to access code in `numpy`. Then type the function or tool you want to use from the `numpy` module.

For example, that would look like
```python
np.array()
```
which would access `numpy`'s `array` tool.

The `array` function is how you convert a list to an array, which is a different *data type*. See below.

In [ ]:
mylist = [1, 2, 3, 4, 5]

myarr = np.array(mylist)

print(type(mylist), type(myarr))

<class 'list'> <class 'numpy.ndarray'>


Note: `ndarray` stands for N-dimensional arrays. We will mostly focus on one-dimensional arrays.

Okay. Now that we have our list as an `numpy` array, let's repeat the previous excercise (doubling a list) using the beautiful tools in `numpy`. Here, we can do all that in just one line! See below.

In [ ]:
print(myarr * 2)

[ 2  4  6  8 10]


Wow, that was easy! `numpy` will assume every operation you apply to an array, you want to do for every element in that array. Thus, you can apply any mathematical operation (`+-*/`) to an array and `numpy` will automatically do that operation for every element in the array (instead of looping through it yourself).

Try some out below!

In [ ]:
x = [1, 2, 3]
# convert x to a numpy array
numpy_x = np.array(x)
# either add, subtract, divide, or multiply every element in x by 2
print(numpy_x - 2)

[-1  0  1]


You can also use boolean operations with arrays. Test out what happens when you use a boolean comparison with an array.

In [ ]:
# extra workspace here
x = [2, 4, 6, 8, 10]
# convert x to a numpy array
numpy_x = np.array(x)
# compare x to the number 2 using less than, greater than, or equal to
print(numpy_x == 2)

[ True False False False False]


Extension: What happens when you use the above operations on a list instead of an array?




In [ ]:
# workspace
x = [2, 4, 6, 8, 10]
print(x * 2)
print(x == 2)
print(x < 2)

[2, 4, 6, 8, 10, 2, 4, 6, 8, 10]
False


TypeError: ignored

Also unlike a list, you can index arrays with another list or array.

In [ ]:
myarr = np.array([1, 3, 5, 7, 9])
print(myarr[[2,4]])

[5 9]


### Common `numpy` Functions

Here are some other useful `numpy` tools that you can use.

Say you have a `numpy` array called `x`.

1. `np.sum(x)` -- find the sum (total) of all elements of the array `x`
2. `np.average(x)` -- find the mean, or average, of all elements of the array `x`
3. `np.median(x)` -- find the median, or middle number, of all elements of the array `x`
4. `np.min(x)` -- find the smallest, or minimum, of all elements of the array `x`
5. `np.max(x)` -- find the largest, or maximum, of all elements of the array `x`
6. `np.sort(x)` -- sort all elements of the array `x` from lowest to highest

**Exercise:** Try out each of the above `numpy` tools on the array `x` below. Print all your results.

In [ ]:
x = np.array([2, 9, 4, 3, 6, 2, 7, 9])
# your code here
numpy_x = np.array(x)
print(np.sum(x))
print(np.average(x))
print(np.median(x))
print(np.min(x))
print(np.max(x))
print(np.sort(x))


42
5.25
5.0
2
9
[2 2 3 4 6 7 9 9]


### Other ways to get a `numpy` array

There are lots of functions provided by the `numpy` library that will create functions. Try some of them out below to get a feel for how they work!

#### `np.random`
Let's revisit the random functions from Module 4! There are a few ways to make an array of random numbers. We used `randint(low, high, length)` which will give us `length` random integers in the range `[low, high)`.

In [ ]:
low = 10
high = 50
length = 5
print(np.random.randint(low, high, length))

[34 12 37 12 30]


You can also use `rand()` which will give you random `float`s in the range `[0, 1)`.

In [ ]:
length = 3
print(np.random.rand(length))

[0.89920878 0.36747332 0.64183544]


#### `np.arange()`
The `np.arange()` tool works just like `range` (from the loops lesson). However, it saves all values into an array.

In [ ]:
start = 1 # feel free to change the numbers here
stop = 6
# default step is 1
x = np.arange(start, stop)
print(x)

start = 10
stop = 100
step = 12
x = np.arange(start, stop, step)
print(x)

[1 2 3 4 5]
[10 22 34 46 58 70 82 94]


#### `np.linspace()`

The `np.linspace()` function generates an array of evenly spaced numbers between two values. Unlike `arange()` the values in this array can be `float`s.


In [ ]:
min_value = 8
max_value = 12
number_of_elements = 10
linarray = np.linspace(min_value, max_value, number_of_elements)
print(linarray)

[ 8.          8.44444444  8.88888889  9.33333333  9.77777778 10.22222222
 10.66666667 11.11111111 11.55555556 12.        ]


**Exercise:** Change `z` such that the elements in `z` are the same as the elements in `x`.

In [ ]:
x = np.arange(1, 6)

### change z here
z = np.linspace(1, 5, 5)
###

print(f'x = {x}')
print(f'z = {z}')
print(z == x)

x = [1 2 3 4 5]
z = [1. 2. 3. 4. 5.]
[ True  True  True  True  True]


#### `np.zeros()`
The `zeros()` function will give you an array of a certain size that is filled with zeros. This can be useful if you know what size you want your array to be, but you need to do something more complicated to fill in the values later.

In [ ]:
length = 8
print(np.zeros(length))

[0. 0. 0. 0. 0. 0. 0. 0.]
